### ISSUE TITLE
Короткие названия отчетов

### ISSUE THREAD

**Issue by Mimir0n** [Mimir0n/avtograf#3]
avtograf.py должен сразу формировать короткие названия, пригодные для сборщика.

**Comment by Mimir0n** [comment]
Лера, какой лимит по количеству символов в названии файла актуален для сборщика?

**Comment by xlebobulka** [comment]
+ reply@
- notifications@

Чем меньше - тем лучше. Также не должно быть никаких посторонних символов, кроме цифр и букв.

12.01.2015, 19:13, "Mimir0n" <notifications@github.com>:
> Лера, какой лимит по количеству символов в названии файла актуален для сборщика?
>
> —
> Reply to this email directly or view it on GitHub.

-- 
Лера Пуглаченко
 +7(916)787-18-69
http://staff.yandex-team.ru/leroy/

**Comment by Mimir0n** [comment]
Нужно более точно, я просто хочу сделать название вида [client][category][1...n], где клиента и категорию ограничить по длине символов, а значит нужен лимит по верхней границе.

**Comment by Mimir0n** [comment]
Готово.
